"""add gmail connections table

Revision ID: 012bebdbf99f
Revises: a2aa7db8d3c6
Create Date: 2026-07-30 09:12:40.114877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012bebdbf99f'
down_revision: Union[str, Sequence[str], None] = 'a2aa7db8d3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_address', sa.String(length=320), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('history_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_connections_gmail_address'), 'gmail_connections', ['gmail_address'], unique=False)
    op.create_index(op.f('ix_gmail_connections_is_active'), 'gmail_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_gmail_connections_organization_id'), 'gmail_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gmail_connections_user_id'), 'gmail_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_connections_user_id'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_organization_id'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_is_active'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_gmail_address'), table_name='gmail_connections')
    op.drop_table('gmail_connections')
    # ### end Alembic commands ###
