"""Add Gmail message models

Revision ID: 0da8d227fc23
Revises: 012bebdbf99f
Create Date: 2026-07-31 17:32:40.447047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da8d227fc23'
down_revision: Union[str, Sequence[str], None] = '012bebdbf99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('gmail_connection_id', sa.UUID(), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('participant_emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('unread', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gmail_connection_id'], ['gmail_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_connection_id', 'provider_thread_id', name='uq_email_thread_provider')
    )
    op.create_index(op.f('ix_email_threads_gmail_connection_id'), 'email_threads', ['gmail_connection_id'], unique=False)
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_email_threads_organization_id'), 'email_threads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_threads_provider_thread_id'), 'email_threads', ['provider_thread_id'], unique=False)
    op.create_index(op.f('ix_email_threads_subject'), 'email_threads', ['subject'], unique=False)
    op.create_index(op.f('ix_email_threads_unread'), 'email_threads', ['unread'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('gmail_connection_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=False),
    sa.Column('internet_message_id', sa.String(length=998), nullable=True),
    sa.Column('in_reply_to', sa.Text(), nullable=True),
    sa.Column('references_header', sa.Text(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('recipient_emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cc_emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('unread', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_attachments', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gmail_connection_id'], ['gmail_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_connection_id', 'provider_message_id', name='uq_email_message_provider')
    )
    op.create_index(op.f('ix_email_messages_direction'), 'email_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_email_messages_gmail_connection_id'), 'email_messages', ['gmail_connection_id'], unique=False)
    op.create_index(op.f('ix_email_messages_has_attachments'), 'email_messages', ['has_attachments'], unique=False)
    op.create_index(op.f('ix_email_messages_internet_message_id'), 'email_messages', ['internet_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_organization_id'), 'email_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_message_id'), 'email_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_thread_id'), 'email_messages', ['provider_thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_received_at'), 'email_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_email_messages_sender_email'), 'email_messages', ['sender_email'], unique=False)
    op.create_index(op.f('ix_email_messages_sent_at'), 'email_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_messages_subject'), 'email_messages', ['subject'], unique=False)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_messages_unread'), 'email_messages', ['unread'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_unread'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_subject'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sent_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sender_email'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_received_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_organization_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_internet_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_has_attachments'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_gmail_connection_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_direction'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_email_threads_unread'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_subject'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_provider_thread_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_organization_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_gmail_connection_id'), table_name='email_threads')
    op.drop_table('email_threads')
    # ### end Alembic commands ###
